version: '3'
services:
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '5000:5000'
    restart: on-failure
    container_name: web-app
  to-do-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: on-failure
    container_name: to-do-api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
    